@startuml

class HentDokumentResultat {
    +dokument: Dokument
}

HentDokumentResultat -- Dokument

class Dokument {
    +systemId: string
    +tittel: string
    +filnavn: string
    +dokumenttype: Kode
    +referanseDokumentfil: string
    +mimetype: string
    +dokumentsdato: date
    +variantformat: Kode
    +dokumentnummer: number
    +dokumentstatus: Kode
    +format: Kode
    +tilknyttetRegistreringSom: Kode
    +referanseTilJournalpost: ReferanseTilJournalpost
    
}

Dokument -- Kode
Dokument -- ReferanseTilJournalpost

class ReferanseTilJournalpost {
    +systemId: string
    +registreringsID: string
    +journalnummer: Journalnummer
    +saksJournalpostnummer: SaksJournalpostnummer
    +referanseEksternNoekkel: ReferanseEksternNoekkel
}

ReferanseTilJournalpost -- Journalnummer
ReferanseTilJournalpost -- SaksJournalpostnummer
ReferanseTilJournalpost -- ReferanseEksternNoekkel

class ReferanseEksternNoekkel {
    +fagsystem: string
    +noekkel: string
}

class Journalnummer {
    +journalaar: number
    +journalsekvensnummer: number
}


class SaksJournalpostnummer {
    +journalpostnummer: string
    +saksaar: number
    +sakssekvensummer: number
}

@enduml