@startuml

class HentPosisjonResultat {
    +punkt: Posisjon
}

HentPosisjonResultat -- Posisjon

class Posisjon {
    +type: string
    +koordinater: number[2-*]
    +koordinatsystem: Kode
}

Posisjon -- Koordinatsystem

class Koordinatsystem<<Kode>> {
    +kodeverdi: string
    +kodebeskrivelse: string
}

@enduml