@startuml
class HentNabolisteResultat {
    naboeiendommer: Eiendom[]
}

HentNabolisteResultat .. Eiendom

class Eiendom {
    * matrikkelnummer: Matrikkelnummer
    eiere: Eier[]
    eiendomadresser: Adresse[]
}

note top of Eiendom : Kan vi kutte ut å returnere eiere?

Eiendom .. Matrikkelnummer

class Matrikkelnummer {
    *kommunenummer: string
    *gaardsnummer: integer
    *bruksnummer: integer
    festenummer: integer
    seksjonsnummer: integer
}


Eiendom *.. Adresse
Eiendom *.. Eier

class Adresse {
    adressetype: Adressetype<<Kode>>
    adresselinje1: string
    adresselinje2: string
    postadresse: Postadresse<<Kode>>
    landkode: Landkode<<Kode>>
}

class Eier {
    *eierforhold: Eierforhold<<Kode>>
    *andel: Andel<<Kode>>
}

note top of Eier : Eierforhold kommer fra matrikkel

class KontaktEier extends Eier
class MatrikkelEier extends Eier

class KontaktEier {
    *kontakt: Kontakt
}

KontaktEier .. Kontakt

class MatrikkelEier {
    *matrikkelnummer: Matrikkelnummer
}

MatrikkelEier .. Matrikkelnummer

class Kontakt {
    *navn: string
}

note top of Kontakt : Denne bør være lik som datamodellen i Fiks Arkiv

class KontaktPerson {
    *personid: string
    *etternavn: string
    *fornavn: string
}


class KontaktOrganisasjon {
    *organisasjonsnummer: string
}

class KontaktPerson extends Kontakt
class KontaktOrganisasjon extends Kontakt

@enduml