@startuml

class HentFlateResultat {
    +omraade: Flate
}

HentFlateResultat -- Flate

class Flate {
    +type: string
    +koordinater: array[number[]]
    +koordinatsystem: Kode
}

Flate -- Kode

@enduml